version: "3.8"

services:
  base:
    build:
      context: .
      dockerfile: Dockerfile.base
    image: mirial-base:latest

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "8005:8000"
    environment:
      - DB_HOST=host.docker.internal
      - DB_PORT=<add port here>
      - DB_USER=<add user here>
      - DB_PASSWORD=<add password here>
      - DB_NAME=<add database name here>
      - SCRAPER_SERVICE_URL=http://scraper:8001
      - VECTORIZER_SERVICE_URL=http://vectorizer:8000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - base
      - scraper
      - vectorizer
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  scraper:
    build:
      context: .
      dockerfile: scraper/Dockerfile
    ports:
      - "8001:8001"
    environment:
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=Srnnkp@4999
      - DB_NAME=mirialdbdev
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - base
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  vectorizer:
    build:
      context: .
      dockerfile: Vectorizer/Dockerfile
    ports:
      - "8002:8000"
    environment:
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=Srnnkp@4999
      - DB_NAME=mirialdbdev
      - OLLAMA_API_URL=http://ollama-rag:8000
      - PYTHONPATH=/app/Vectorizer:/app/shared:/app
    volumes:
      - ./Vectorizer:/app/Vectorizer
      - ./shared:/app/shared
      - vectorstore_data:/app/vectorstore
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - base
      - ollama-rag
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  ollama-rag:
    build:
      context: ./mistral
      dockerfile: Dockerfile
    ports:
      - "11434:11434"
      - "8006:8000"
    volumes:
      - ./mistral:/app/mistral
      - vectorstore_data:/app/vectorstore
      - ollama_data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    restart: unless-stopped

volumes:
  ollama_data:
  vectorstore_data:
